env:
    browser: true
    es6: true
parser: '@typescript-eslint/parser'
plugins:
    - '@typescript-eslint'
extends:
    - plugin:@typescript-eslint/recommended
parserOptions:
    ecmaVersion: 2018
    sourceType: module
    project: './tsconfig.json'
rules:
    '@typescript-eslint/prefer-interface': off
    '@typescript-eslint/indent': off
    '@typescript-eslint/explicit-function-return-type': off
    '@typescript-eslint/no-non-null-assertion': off
    '@typescript-eslint/ban-types': off
    '@typescript-eslint/no-explicit-any': off
    '@typescript-eslint/array-type': [error, {default: 'generic'}]
