name: CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest]
                node_version: [12]
        name: CI on NodeJS v${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        steps:
            - run: git config --global core.autocrlf false
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
            - run: npm ci
            - run: npm run prepublishOnly
