name: CI
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    merge_group:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
            - run: yarn install --immutable
            - run: yarn lint
            - run: yarn prettier-check
            - run: yarn build
            - run: yarn ts-check
            - run: yarn test --ci
