name: Release
on:
    workflow_dispatch:
        inputs:
            cliArgs:
                description: 'CLI args'
                required: false
                default: ''
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - run: yarn install --immutable --immutable-cache

            - name: Set npm token
              uses: actions/github-script@v7
              env:
                  NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
              with:
                  script: |
                      if (!process.env.NPM_TOKEN) {
                          throw new Error('NPM_TOKEN env var not set');
                      }

                      const lines = [
                          // set npm auth token with publish permission from environment
                          `//registry.npmjs.org/:_authToken=${process.env.NPM_TOKEN}`,

                          // this allows to execute npm lifecycle scripts by root
                          'unsafe-perm = true',
                      ];

                      fs.writeFileSync('.npmrc', lines.join('\n'));

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.FLOW_GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
              run: npx semantic-release ${{ github.event.inputs.cliArgs }}
